const Data = [
    { item: "Leo", isAdded: false },
    { item: "RedX", isAdded: false },
    { item: "GwenDem", isAdded: false },
    { item: "Nigar", isAdded: false },
    { item: "Nishant", isAdded: false },
    { item: "Rupali", isAdded: false },
    { item: "Rupa", isAdded: false },
    { item: "Rudra", isAdded: false },
    { item: "Leone", isAdded: false },
    { item: "Wokosh", isAdded: false },
    { item: "Shokosh", isAdded: false },
    { item: "Worsh", isAdded: false },
    { item: "Fabian", isAdded: false },
    { item: "Faith", isAdded: false },
    { item: "Fannie", isAdded: false },
    { item: "Nakita", isAdded: false },
    { item: "Nanna", isAdded: false },
    { item: "Sabrina", isAdded: false },
    { item: "Nada", isAdded: false },
    { item: "Sabastian", isAdded: false },
  ];
  export default Data;